ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym "A"
  inflect.acronym "AAAA"
  inflect.acronym "ALIAS"
  inflect.acronym "CAA"
  inflect.acronym "CNAME"
  inflect.acronym "HINFO"
  inflect.acronym "MX"
  inflect.acronym "NAPTR"
  inflect.acronym "NS"
  inflect.irregular "NS", "NSes"
  inflect.acronym "NSes"
  inflect.acronym "PTR"
  inflect.acronym "SRV"
  inflect.acronym "SPF"
  inflect.acronym "SSHFP"
  inflect.acronym "TXT"
  inflect.acronym "URL"
end
